Repository trufi-association/trufi-core, pull requests merged in 2021-04, with the labels that each got.

#401 🐱‍🏍[DevOps] GitHub Actions free CI / CD
  .github/workflows/flutter_test.yml
Labels: DevOps

#406 🐱‍🏍[DevOps] Fixed the pipeline
  .github/workflows/flutter_test.yml
  README.md
Labels: DevOps

#405 💬 [Documentation] Add a Code of Conduct and a Contribution file
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: Documentation

#408 💬[Documentation] Add Issue Template for Bug Report and Feature Request
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation

#411 👌 [Quality Improvement] Cleaned warning Android Embedding V2
  example/android/app/src/main/AndroidManifest.xml
  example/android/app/src/main/kotlin/app/trufi/trufi_core_example/MainActivity.kt
Labels: Quality Improvement

#393 Feature/custom widget
  example/lib/main.dart
  lib/pages/home.dart
  lib/plan/plan.dart
  lib/plan/plan_empty.dart
  lib/plan/plan_itinerary_tabs.dart
  lib/plan/plan_map.dart
  lib/trufi_app.dart
  test/widget_test/trufi_app_test.dart
Labels: enhancement

#418 Improved the OfflineRequestManager fetchLocations
  lib/blocs/favorite_locations_bloc.dart
  lib/blocs/location_search_bloc.dart
  lib/blocs/locations_bloc_base.dart
  lib/blocs/request_manager/offline_request_manager.dart
  lib/blocs/request_manager/online_request_manager.dart
  lib/blocs/request_manager_bloc.dart
  lib/location/location_search_delegate.dart
  lib/location/location_search_storage.dart
  lib/trufi_models.dart
  test/blocs/request_manager/offline_request_manager_test.dart
Labels: Quality Improvement

#420 🛠 [Refactoring] State Management improvement with the Bloc Package
  example/lib/main.dart
  lib/blocs/app_review_bloc.dart
  lib/blocs/app_review_cubit.dart
  lib/blocs/bloc_provider.dart
  lib/blocs/favorite_location_bloc.dart
  lib/blocs/favorite_locations_bloc.dart
  lib/blocs/history_locations_bloc.dart
  lib/blocs/home_page_cubit.dart
  lib/blocs/location_provider_bloc.dart
  lib/blocs/location_search_bloc.dart
  lib/blocs/preferences_bloc.dart
  lib/blocs/preferences_cubit.dart
  lib/blocs/request_manager_bloc.dart
  lib/blocs/request_manager_cubit.dart
  lib/blocs/saved_places_bloc.dart
  lib/location/location_search_delegate.dart
  lib/models/map_route_state.dart
  lib/models/preferences.dart
  lib/pages/home.dart
  lib/pages/home_page.dart
  lib/pages/saved_places.dart
  lib/plan/plan.dart
  lib/repository/exception/fetch_online_exception.dart
  lib/repository/local_repository.dart
  lib/repository/offline_repository.dart
  lib/repository/online_repository.dart
  lib/repository/request_manager.dart
  lib/repository/shared_preferences_repository.dart
  lib/trufi_app.dart
  lib/trufi_configuration.dart
  lib/trufi_observer.dart
  lib/widgets/alerts.dart
  lib/widgets/map_type_button.dart
  lib/widgets/trufi_drawer.dart
  lib/widgets/trufi_on_and_offline_map.dart
  lib/widgets/trufi_online_map.dart
  pubspec.lock
  pubspec.yaml
  test/blocs/app_review_cubit_test.dart
  test/blocs/home_page_cubit_test.dart
  test/blocs/preferences_cubit_test.dart
  test/mocks/favorite_locations_bloc.dart
  test/mocks/local_repository_mock.dart
  test/mocks/location_search_bloc.dart
  test/mocks/request_manager_mock.dart
  test/mocks/uuid_mock.dart
  test/repository/offline_repository_test.dart
  test/widgets/trufi_drawer_test.dart
Labels: Quality Improvement

#427 [BugFix] Stop fetching after the plan receives an error
  lib/blocs/home_page_cubit.dart
Labels: bug

#430 [Refactor] Cleanup LocationProviderBloc
  example/android/app/src/debug/AndroidManifest.xml
  example/android/app/src/main/AndroidManifest.xml
  example/android/app/src/profile/AndroidManifest.xml
  lib/blocs/location_provider_bloc.dart
  lib/blocs/location_provider_cubit.dart
  lib/location/location_search_delegate.dart
  lib/models/location_state.dart
  lib/pages/choose_location.dart
  lib/pages/home_page.dart
  lib/pages/saved_places.dart
  lib/plan/plan_empty.dart
  lib/plan/plan_map.dart
  lib/trufi_app.dart
  lib/widgets/trufi_map.dart
  pubspec.lock
  pubspec.yaml
  test/blocs/location_provider_cubit_test.dart
  test/mocks/geolocator_mock.dart
Labels: Quality Improvement

#437 🐞 [BugFix] Solution for SearchBarTheme
  lib/blocs/theme_bloc.dart
  lib/location/location_search_delegate.dart
  lib/models/theme_state.dart
  lib/trufi_app.dart
  lib/widgets/alerts.dart
Labels: Quality Improvement, bug

#438 Improvement/fetch manager
  example/ios/Runner.xcodeproj/project.pbxproj
  lib/blocs/home_page_cubit.dart
  lib/blocs/request_search_manager_cubit.dart
  lib/location/location_search_delegate.dart
  lib/pages/home_page.dart
  lib/pages/saved_places.dart
  lib/repository/exception/fetch_online_exception.dart
  lib/repository/offline_repository.dart
  lib/repository/online_repository.dart
  lib/repository/request_manager.dart
  lib/trufi_app.dart
  lib/widgets/fetch_error_handler.dart
  test/blocs/home_page_cubit_test.dart
Labels: enhancement

#432 [Feat] Add support to graphql with simple HTTP request
  lib/repository/online_graphql_repository/online_graphql_repository.dart
  lib/repository/online_graphql_repository/plan_graphql_model.dart
  lib/repository/online_graphql_repository/queries.dart
  lib/trufi_configuration.dart
  test/repository/online_graphql_repository/queries_test.dart
Labels: enhancement
