Repository trufi-association/trufi-core, pull requests merged in 2021-05, with the labels that each got.

#452 Feat/Settings Panel
  lib/blocs/home_page_cubit.dart
  lib/entities/plan_entity/plan_entity.dart
  lib/entities/plan_entity/plan_itinerary_leg.dart
  lib/models/enums/bike_rental_network.dart
  lib/models/enums/biking_speed.dart
  lib/models/enums/optimize_type.dart
  lib/models/enums/plan_enums.dart
  lib/models/enums/transport_mode.dart
  lib/models/enums/walk_board_cost.dart
  lib/models/enums/walking_speed.dart
  lib/models/map_route_state.dart
  lib/pages/home/home_page.dart
  lib/pages/home/plan_map/plan_map.dart
  lib/pages/home/plan_map/setting_panel/setting_panel.dart
  lib/pages/home/plan_map/setting_panel/setting_panel_cubit.dart
  lib/pages/home/plan_map/setting_panel/setting_panel_state.dart
  lib/pages/saved_places.dart
  lib/repository/local_repository.dart
  lib/repository/shared_preferences_repository.dart
  lib/services/plan_request/online_graphql_repository/online_graphql_repository.dart
  lib/services/plan_request/online_graphql_repository/plan_graphql_model.dart
  lib/services/plan_request/online_graphql_repository/queries.dart
  lib/services/plan_request/online_repository.dart
  lib/services/plan_request/request_manager.dart
  lib/trufi_app.dart
  lib/widgets/custom_expanded_tile.dart
  lib/widgets/custom_switch_tile.dart
  lib/widgets/map_setting_button.dart
  test/repository/online_graphql_repository/queries_test.dart
Labels: enhancement

#456 [Feature] Add Weather information to Trufi Core
  lib/repository/entities/weather_info.dart
  lib/repository/weather_data.dart
  lib/repository/wfs_weather_data_repository.dart
  pubspec.lock
  pubspec.yaml
  test/repository/wfs_weather_data_repository_test.dart
Labels: enhancement

#464 [Refactor] Removed the Configuration Singleton
  example/lib/configuration_service.dart
  example/lib/main.dart
  example/pubspec.yaml
  lib/blocs/app_review_cubit.dart
  lib/blocs/configuration/configuration.dart
  lib/blocs/configuration/configuration_cubit.dart
  lib/blocs/configuration/models/animation_configuration.dart
  lib/blocs/configuration/models/attribution.dart
  lib/blocs/configuration/models/language_configuration.dart
  lib/blocs/configuration/models/map_configuration.dart
  lib/blocs/configuration/models/url_collection.dart
  lib/location/location_search_delegate.dart
  lib/models/definition_feedback.dart
  lib/models/enums/server_type.dart
  lib/pages/about.dart
  lib/pages/choose_location.dart
  lib/pages/feedback.dart
  lib/pages/home/form_fields_landscape.dart
  lib/pages/home/form_fields_portrait.dart
  lib/pages/home/home_page.dart
  lib/pages/home/plan_map/plan.dart
  lib/pages/home/plan_map/plan_empty.dart
  lib/pages/home/plan_map/plan_map.dart
  lib/pages/home/search_location/location_form_field.dart
  lib/pages/saved_places/location_tiler.dart
  lib/pages/team.dart
  lib/trufi_app.dart
  lib/trufi_configuration.dart
  lib/trufi_models.dart
  lib/widgets/fetch_error_handler.dart
  lib/widgets/map/map_copyright.dart
  lib/widgets/map/trufi_map.dart
  lib/widgets/map/trufi_map_controller.dart
  lib/widgets/trufi_drawer.dart
  test/blocs/app_review_cubit_test.dart
  test/l10n/trufi_custom_localization_test.dart
  test/trufi_app_test.dart
  test/widgets/trufi_drawer_test.dart
  test_driver/home.dart
Labels: Quality Improvement

#469 [Feature] remove all history
  lib/blocs/search_locations/search_locations_cubit.dart
  lib/repository/places_store_repository/shared_preferences_place_storage.dart
Labels: bug

#473 🚀 [DevOps] Fixed build pipeline and optimized
  .github/workflows/flutter_test.yml
Labels: DevOps

#472 fix small issues
  lib/pages/choose_location.dart
  lib/pages/home/setting_payload/date_time_picker/itinerary_date_selector.dart
  lib/services/plan_request/online_graphql_repository/queries.dart
Labels: bug

#475 ☀️ [Feature] Weather Information
  README.md
  assets/images/weather/1.svg
  assets/images/weather/2.svg
  assets/images/weather/21.svg
  assets/images/weather/22.svg
  assets/images/weather/23.svg
  assets/images/weather/3.svg
  assets/images/weather/31.svg
  assets/images/weather/32.svg
  assets/images/weather/33.svg
  assets/images/weather/41.svg
  assets/images/weather/42.svg
  assets/images/weather/43.svg
  assets/images/weather/51.svg
  assets/images/weather/52.svg
  assets/images/weather/53.svg
  assets/images/weather/61.svg
  assets/images/weather/62.svg
  assets/images/weather/63.svg
  assets/images/weather/64.svg
  assets/images/weather/71.svg
  assets/images/weather/72.svg
  assets/images/weather/73.svg
  assets/images/weather/81.svg
  assets/images/weather/82.svg
  assets/images/weather/83.svg
  assets/images/weather/91.svg
  assets/images/weather/92.svg
  lib/blocs/configuration/configuration.dart
  lib/blocs/preferences/preferences.dart
  lib/blocs/preferences/preferences_cubit.dart
  lib/repository/entities/weather_info.dart
  lib/repository/wfs_weather_data_repository.dart
  lib/trufi_app.dart
  lib/widgets/trufi_drawer.dart
  pubspec.yaml
  test/widgets/trufi_drawer_test.dart
Labels: enhancement

#476 Feat/Bottom itinerary details
  example/lib/main.dart
  example/lib/theme/theme.dart
  lib/blocs/theme_bloc.dart
  lib/entities/plan_entity/place_entity.dart
  lib/entities/plan_entity/plan_entity.dart
  lib/entities/plan_entity/plan_entity_utils.dart
  lib/entities/plan_entity/plan_itinerary.dart
  lib/entities/plan_entity/plan_itinerary_leg.dart
  lib/entities/plan_entity/stop_entity.dart
  lib/models/theme_state.dart
  lib/pages/home/plan_map/plan_itinerary_tabs.dart
  lib/pages/home/plan_map/plan_itinerary_tabs/itinerary_details_collapsed.dart
  lib/pages/home/plan_map/plan_itinerary_tabs/itinerary_details_expanded.dart
  lib/pages/home/plan_map/plan_itinerary_tabs/itinerary_details_expanded/leg_overview.dart
  lib/pages/home/plan_map/plan_itinerary_tabs/itinerary_details_expanded/leg_overview_advenced/bar_itinerary_details.dart
  lib/pages/home/plan_map/plan_itinerary_tabs/itinerary_details_expanded/leg_overview_advenced/leg_overview_advenced.dart
  lib/pages/home/plan_map/plan_itinerary_tabs/itinerary_details_expanded/leg_overview_advenced/line_dash_components.dart
  lib/pages/home/plan_map/plan_itinerary_tabs/transport_icon_detail.dart
  lib/services/plan_request/online_graphql_repository/online_graphql_repository.dart
  lib/services/plan_request/online_graphql_repository/plan_graphql_model.dart
  lib/services/plan_request/online_graphql_repository/queries.dart
  lib/trufi_app.dart
  lib/widgets/map/utils/trufi_map_utils.dart
  test/repository/online_graphql_repository/queries_test.dart
  test/trufi_models_plan_unit_test.dart
Labels: enhancement

#479 Feat/adding translations
  lib/blocs/home_page_cubit.dart
  lib/blocs/search_locations/search_locations_cubit.dart
  lib/entities/plan_entity/plan_entity_utils.dart
  lib/entities/plan_entity/plan_itinerary_leg.dart
  lib/l10n/trufi_localization.dart
  lib/l10n/trufi_localization_de.dart
  lib/l10n/trufi_localization_ee.dart
  lib/l10n/trufi_localization_en.dart
  lib/l10n/trufi_localization_es.dart
  lib/l10n/trufi_localization_fr.dart
  lib/l10n/trufi_localization_it.dart
  lib/l10n/trufi_localization_pt.dart
  lib/l10n/trufi_localization_qu.dart
  lib/location/location_search_delegate.dart
  lib/models/custom_layer.dart
  lib/models/enums/enums_plan/biking_speed.dart
  lib/models/enums/enums_plan/walking_speed.dart
  lib/pages/home/home_page.dart
  lib/pages/home/plan_map/plan_empty.dart
  lib/pages/home/plan_map/plan_itinerary_tabs/itinerary_details_expanded/leg_overview_advenced/line_dash_components.dart
  lib/pages/home/setting_payload/date_time_picker/date_time_picker.dart
  lib/pages/home/setting_payload/date_time_picker/itinerary_date_selector.dart
  lib/pages/home/setting_payload/setting_panel/map_setting_button.dart
  lib/pages/home/setting_payload/setting_panel/setting_panel.dart
  lib/pages/saved_places/saved_places.dart
  lib/trufi_models.dart
  lib/widgets/custom_expanded_tile.dart
  lib/widgets/fetch_error_handler.dart
  lib/widgets/map/buttons/map_type_button.dart
  test/blocs/home_page_cubit_test.dart
  translations/trufiapp_de.arb
  translations/trufiapp_ee.arb
  translations/trufiapp_en.arb
  translations/trufiapp_es.arb
  translations/trufiapp_fr.arb
  translations/trufiapp_it.arb
  translations/trufiapp_pt.arb
  translations/trufiapp_qu.arb
Labels: enhancement
